services:
  webproject:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    volumes:
      - ./config:/app/config
      - ./templates:/app/templates
      - ./static:/app/static
      - ./log:/app/log
    restart: unless-stopped
